version: '2'

networks:
  diplo_network:
    #external:
    #  name: nginxproxynetwork
    external: false

volumes:
  diplo_es:

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: diplo_es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
    volumes:
    #  - diplo_es:/usr/share/elasticsearch/data
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - diplo_network

  kibana:
      image: docker.elastic.co/kibana/kibana:7.5.2
      environment:
        ELASTICSEARCH_URL: http://elastic:9200
        ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'    
      ports:
        - 5601:5601 
      networks:
        - diplo_network         

  # pyservice_prod:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   container_name: diplo_service
  #   environment:
  #     - VIRTUAL_HOST=diploservice.sd.di.huc.knaw.nl
  #   ports:
  #     - 5050:5000
  #   volumes:
  #     - ./data:/data
  #   networks:
  #     - diplo_network

  pyservice:
    build:
        context: ./
        dockerfile: DockerfileMaart
    ports:
      - 5050:5000
    environment:
      USER: test
      PASSWORD: test

    volumes:
      - ./data:/data
      - ./src:/usr/src/app

    networks:
      - diplo_network      
